- name: build cmb frontend microservice
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    #install collections
    - name: install collections
      shell: "ansible-galaxy collection install {{ item | quote }} --force"
      loop:
        - community.docker:<=3.4.3
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,ctdc

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1
        project_name: "{{ lookup('env','PROJECT_NAME') }}"
        tier: "{{ tier }}"
        ecr_account: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.ecr_account', nested=true, region='us-east-1' ) }}"


    #frontend build
    - name: build frontend
      include_role:
        name: bento.common.build_cmb_frontend
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER') }}"
        project_name: "{{ project_name }}"
        image_version: "{{ lookup('env','FE_VERSION') }}"
        container_name: "frontend"
        container_build_path: "{{ workspace }}/{{ project_name }}-frontend"
        dockerfile_path: "{{ workspace }}/${env.PROJECT}-frontend/Dockerfile"
        container_registry_url: "{{ ecr_repo }}"