- name: build backend microservice
  hosts: all
  connection: local
  gather_facts: no
  
  tasks:
    #install collections
    - name: install aws collection
      shell: "ansible-galaxy collection install {{ item | quote }} --force"
      loop:
        - community.docker:<=3.4.3
        #- git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,ctdc

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1

    - name: log into ncidockerhub
      community.docker.docker_login:
        username: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.docker_user', nested=true, region='us-east-1') }}"
        password: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.docker_password', nested=true, region='us-east-1') }}"
        registry: https://ncidockerhub.nci.nih.gov

    #build backend
    - name: build {{ project_name }} backend
      include_role:
        name: bento.common.build_backend
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER')}}"
        project_name: "{{ lookup('env','PROJECT_NAME') }}"
        project: "{{ project_name }}"
        image_version: "{{ lookup('env','BE_VERSION') }}"
        tier: "{{ tier }}"
        bento_api_version: "{{ image_version }}"
        container_name: "backend"
        schema_file: "{{ project_name }}.graphql"
        es_schema_file: "es-schema-{{ project_name }}.graphql"
        es_host: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.es_host', nested=true, region='us-east-1' ) }}"
        test_queries_file: "not_needed.txt"
        dockerfile_path: "{{ workspace }}/playbooks/docker/dockerfiles/backend-ctdc-dockerfile"
        container_image: "{{ ecr_repo }}/{{ project_name }}-{{ container_name }}:{{ image_version }}"
        container_registry_url: "{{ ecr_repo }}"
        #auth_enabled: "false"